spring.application.name=orchestrator

# ========== SERVICE ROUTING CONFIGURATION ==========
services.user.name=user-service
services.user.uri=http://13.124.4.121:8080

services.alarm.name=alarm-service
services.alarm.uri=http://15.164.82.42:8080

services.auth.name=auth-service
services.auth.uri=http://43.201.165.118:8080

services.transaction-feed.name=transaction-feed-service
services.transaction-feed.uri=http://3.36.18.51:8080

services.pay.name=pay-service
services.pay.uri=http://52.78.14.23:8080

services.statistics.name=statistics-service
services.statistics.uri=http://43.200.49.85:8080

services.admin.name=admin-service
services.admin.uri=http://3.39.218.134:8080